# Generated by Django 4.1.1 on 2022-10-14 08:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=100, verbose_name='Category name')),
                ('category_slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('category_name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=255, verbose_name='Name')),
                ('product_slug', models.SlugField(max_length=255)),
                ('product_image', models.ImageField(blank=True, upload_to='images/product_imgs/', verbose_name='Image')),
                ('product_description', models.TextField(blank=True, verbose_name='Description')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Price')),
                ('product_is_aviable', models.BooleanField(default=True, verbose_name='Availability')),
                ('product_created', models.DateTimeField(auto_now_add=True)),
                ('product_updated', models.DateTimeField(auto_now=True)),
                ('characteristics', models.JSONField(default=None)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='webshop.category', verbose_name='Choise a category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'ordering': ('product_name',),
                'index_together': {('id', 'product_slug')},
            },
        ),
    ]
