# Generated by Django 4.1.1 on 2022-10-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0003_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.CharField(db_index=True, default=None, max_length=200),
        ),
    ]
