# Generated by Django 4.1.1 on 2022-10-17 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0004_alter_product_characteristics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.JSONField(default=dict),
        ),
    ]
