# Generated by Django 4.1.1 on 2023-06-27 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0010_inventory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventory',
        ),
    ]
