# Generated by Django 4.1.1 on 2023-06-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0011_delete_inventory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_name', models.CharField(db_index=True, max_length=100, verbose_name='Stock name')),
                ('stock_slug', models.SlugField(max_length=100, unique=True)),
                ('products', models.ManyToManyField(related_name='stocks', to='webshop.product', verbose_name='Products')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'ordering': ('stock_name',),
            },
        ),
    ]
