# Generated by Django 4.1.1 on 2023-06-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0014_productstock_product_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='products',
            field=models.ManyToManyField(related_name='stocks', through='webshop.ProductStock', to='webshop.product', verbose_name='Products'),
        ),
    ]
