# Generated by Django 4.1.1 on 2023-11-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0016_alter_product_characteristics_historicalcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='historicalcategory',
            name='name',
            field=models.BooleanField(default=True),
        ),
    ]
