# Generated by Django 4.1.1 on 2023-11-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0017_category_name_historicalcategory_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicalcategory',
            name='name',
        ),
    ]
