# Generated by Django 4.1.1 on 2023-11-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webshop', '0018_remove_category_name_remove_historicalcategory_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='historicalcategory',
            name='id',
            field=models.IntegerField(blank=True, db_index=True),
        ),
    ]
